/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package kr.ac.kaist.se.aom.structure.provider;

import java.util.ArrayList;
import java.util.Collection;

import kr.ac.kaist.se.aom.structure.util.StructureAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class StructureItemProviderAdapterFactory extends StructureAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public StructureItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link kr.ac.kaist.se.aom.structure.AOMClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AOMClassItemProvider aomClassItemProvider;

	/**
	 * This creates an adapter for a {@link kr.ac.kaist.se.aom.structure.AOMClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAOMClassAdapter() {
		if (aomClassItemProvider == null) {
			aomClassItemProvider = new AOMClassItemProvider(this);
		}

		return aomClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link kr.ac.kaist.se.aom.structure.AOMField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AOMFieldItemProvider aomFieldItemProvider;

	/**
	 * This creates an adapter for a {@link kr.ac.kaist.se.aom.structure.AOMField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAOMFieldAdapter() {
		if (aomFieldItemProvider == null) {
			aomFieldItemProvider = new AOMFieldItemProvider(this);
		}

		return aomFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link kr.ac.kaist.se.aom.structure.AOMMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AOMMethodItemProvider aomMethodItemProvider;

	/**
	 * This creates an adapter for a {@link kr.ac.kaist.se.aom.structure.AOMMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAOMMethodAdapter() {
		if (aomMethodItemProvider == null) {
			aomMethodItemProvider = new AOMMethodItemProvider(this);
		}

		return aomMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link kr.ac.kaist.se.aom.structure.AOMScope} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AOMScopeItemProvider aomScopeItemProvider;

	/**
	 * This creates an adapter for a {@link kr.ac.kaist.se.aom.structure.AOMScope}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAOMScopeAdapter() {
		if (aomScopeItemProvider == null) {
			aomScopeItemProvider = new AOMScopeItemProvider(this);
		}

		return aomScopeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link kr.ac.kaist.se.aom.structure.AOMParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AOMParameterItemProvider aomParameterItemProvider;

	/**
	 * This creates an adapter for a {@link kr.ac.kaist.se.aom.structure.AOMParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAOMParameterAdapter() {
		if (aomParameterItemProvider == null) {
			aomParameterItemProvider = new AOMParameterItemProvider(this);
		}

		return aomParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link kr.ac.kaist.se.aom.structure.AOMLocalVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AOMLocalVariableItemProvider aomLocalVariableItemProvider;

	/**
	 * This creates an adapter for a {@link kr.ac.kaist.se.aom.structure.AOMLocalVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAOMLocalVariableAdapter() {
		if (aomLocalVariableItemProvider == null) {
			aomLocalVariableItemProvider = new AOMLocalVariableItemProvider(this);
		}

		return aomLocalVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link kr.ac.kaist.se.aom.structure.AOMExternalType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AOMExternalTypeItemProvider aomExternalTypeItemProvider;

	/**
	 * This creates an adapter for a {@link kr.ac.kaist.se.aom.structure.AOMExternalType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAOMExternalTypeAdapter() {
		if (aomExternalTypeItemProvider == null) {
			aomExternalTypeItemProvider = new AOMExternalTypeItemProvider(this);
		}

		return aomExternalTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link kr.ac.kaist.se.aom.structure.AOMLocalVariableAccess} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AOMLocalVariableAccessItemProvider aomLocalVariableAccessItemProvider;

	/**
	 * This creates an adapter for a {@link kr.ac.kaist.se.aom.structure.AOMLocalVariableAccess}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAOMLocalVariableAccessAdapter() {
		if (aomLocalVariableAccessItemProvider == null) {
			aomLocalVariableAccessItemProvider = new AOMLocalVariableAccessItemProvider(this);
		}

		return aomLocalVariableAccessItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (aomClassItemProvider != null) aomClassItemProvider.dispose();
		if (aomFieldItemProvider != null) aomFieldItemProvider.dispose();
		if (aomMethodItemProvider != null) aomMethodItemProvider.dispose();
		if (aomScopeItemProvider != null) aomScopeItemProvider.dispose();
		if (aomParameterItemProvider != null) aomParameterItemProvider.dispose();
		if (aomLocalVariableItemProvider != null) aomLocalVariableItemProvider.dispose();
		if (aomExternalTypeItemProvider != null) aomExternalTypeItemProvider.dispose();
		if (aomLocalVariableAccessItemProvider != null) aomLocalVariableAccessItemProvider.dispose();
	}

}
